name: camera_capture_workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:

jobs:
  download-image:
    runs-on: ubuntu-latest

    env:
      TZ: America/New_York

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up timestamp and Download Image
      id: download
      run: |
        timestamp=$(date +'%Y-%m-%d-%H-%M-%S')
        year=${timestamp:0:4}
        month=${timestamp:5:2}
        day=${timestamp:8:2}

        mkdir -p "images/${year}/${month}/${day}"
        curl -o "images/${year}/${month}/${day}/${timestamp}_Adams_St___Willoughby_St.jpg" https://webcams.nyctmc.org/api/cameras/b59bd3d2-0d72-4a65-8316-e79491c622e3/image

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'nycbikelanes'
        git config --global user.email 'nycbikelanes@users.noreply.github.com'
        git add images/
        git commit -m "Add image for timestamp: $timestamp"
        git push
