name: camera_capture_workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:

jobs:
  download-image:
    runs-on: ubuntu-latest

    env:
      TZ: America/New_York

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Set up timestamp and Download Image
      id: download
      run: |
        export TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        year=${TIMESTAMP:0:4}
        month=${TIMESTAMP:5:2}
        day=${TIMESTAMP:8:2}

        mkdir -p "images/${year}/${month}/${day}"
        mkdir -p "images/60oldfulton/${year}/${month}/${day}"
        curl -o "images/${year}/${month}/${day}/${TIMESTAMP}_Adams_St___Willoughby_St.jpg" https://webcams.nyctmc.org/api/cameras/b59bd3d2-0d72-4a65-8316-e79491c622e3/image
        curl -o "images/60oldfulton/${year}/${month}/${day}/${TIMESTAMP}_60oldfulton.jpg" https://webcams.nyctmc.org/api/cameras/f134b133-75ef-40a8-8fbb-f9c51355e6b5/image

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'nycbikelanes'
        git config --global user.email 'nycbikelanes@users.noreply.github.com'
        git add images/
        git commit -m "Add image for timestamp: $TIMESTAMP"
        git push
